import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
//import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
//import DataDisplay from "@/components/DataDisplay";
import { ApolloClient, InMemoryCache, ApolloProvider, gql } from '@apollo/client';
import { ApolloClientProvider } from "@/components/ApolloWrap";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloClientProvider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </ApolloClientProvider>
  );
}
